### ISSUE TITLE
UNSD Methodology CSV included multiple time

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui#6]
the UNSD Methodology CSV file is included in both the indexer and the regions (with different filenames), this will lead to problems in the future whenever the list is update and not both files are updated. Should only be one file.

**Comment by jmckenna** [comment]
I wonder if we should switch to using a call to the UNSD API, using the `/api/Country` endpoint, instead of maintaining a separate CSV file, such as:
- in your browser: https://unstats.un.org/unsd/amaapi/api/Country?countriesOnly=true
- commandline: 
  ```
  curl -X 'GET' \
  'https://unstats.un.org/unsd/amaapi/api/Country?countriesOnly=true' \
  -H 'accept: */*'
  ```
- see the docs at https://unstats.un.org/unsd/amaapi/swagger/index.html

**Comment by jmckenna** [comment]
At the minimum we should remove the spaces in this filename (it's disaster accessing this file on different platforms, because of the spaces).

**Comment by jmckenna** [comment]
@pbuttigieg fixed now, see details in https://github.com/iodepo/oih-ui/pull/77
