### ISSUE TITLE
no information on all required python3 modules to be installed

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui#8]
the general README file should contain information on all the software that needs to be installed to run the complete suite

till now I  had to:
```
 pip3 install requests
pip3 install shapely
pip3 install conversions
pip3 install python-dateutil
```

**Comment by pieterprovoost** [comment]
Any reason why this is not in Docker like the rest? And there's a `requirements.txt`, so `pip install -r requirements.txt` should do the trick, although it doesn't seem to be complete and is missing version information.

**Comment by EricSoroos** [comment]
Why it's not in docker -- a few reasons, mainly inertia based. 
1) Initial tests were on a laptop, where volume mounting the data directories had performance 10x worse than local filesystem.
2) Putting it in the docker compose is a slight impedance mismatch, because it's a task and done container, and not a server like the others. 

On the other hand, adding it, and the configuration to the docker-compose, would allow for 'hard coding' certain environment variables which would make it less of an issue to configure. 

It looks like the `dateutil` wasn't in the requirements.txt because it was pulled in by the `awscli` (which I had in this venv) for downloading from s3.

**Comment by arnounesco** [comment]
the missing module is now in requirements.txt
